version: '3'
  
services:
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.3
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: ${POSTGRESQL_CONNECTION_URI}
    restart: unless-stopped
