version: '3'
  
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: superadmin 
      POSTGRES_PASSWORD: meefer 
      POSTGRES_DB: supertokens
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - /pg-db:/var/lib/postgresql/data

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.3
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://superadmin:meefer@db:5432/supertokens"
    restart: unless-stopped